# https://taskfile.dev

version: '3'

vars:
  BINARY: keyfob
  BUILD_DIR: bin
  TEST_REPORT: tests.xml
  COVERAGE_RAW: cover.out
  COVERAGE_REPORT: cover.html
  VERSION: "Make"

tasks:
  install:
    desc: Installs Golang dependencies and testing tools.
    cmds:
      - go get ./...
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  
  build:
    desc: Builds bouncer binary.
    cmds:
      - mkdir {{.BUILD_DIR}} | true
      - go build -ldflags "-X main.version=${VERSION}" -o {{.BUILD_DIR}} ./...

  fmt:
    desc: Formats Golang code.
    cmds:
      - go fmt $(go list ./...)
  
  lint:
    desc: Lints Golang code.
    cmds:
      - golangci-lint run