# https://taskfile.dev

version: '3'

vars:
  BINARY: keyfob
  BUILD_DIR: bin
  TEST_REPORT: tests.xml
  COVERAGE_RAW: cover.out
  COVERAGE_REPORT: cover.html
  VERSION: "Make"

tasks:
  default:
    cmds:
      - task: install
      - task: fmt
      - task: lint
      - task: test

  install:
    desc: Installs Golang dependencies and testing tools.
    cmds:
      - go mod tidy
      - go get ./...
  
  build:
    desc: Builds bouncer binary.
    cmds:
      - mkdir {{.BUILD_DIR}} | true
      - go build -ldflags "-X main.version=${VERSION}" -o {{.BUILD_DIR}} ./...

  fmt:
    desc: Formats Golang code.
    cmds:
      - go fmt $(go list ./...)
  
  lint:
    desc: Lints Golang code.
    cmds:
      - golangci-lint run

  test:
    desc: Run Golang tests.
    cmds:
      - go test -v ./... 2>&1
  
  test-ci:
    desc: Run Golang tests and generate coverage report.
    cmds:
      - go test --coverprofile {{.COVERAGE_RAW}} -v ./... 2>&1  | go-junit-report > report.xml
      - go tool cover -html={{.COVERAGE_RAW}} -o {{.COVERAGE_REPORT}}
